// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ZealandEventLib.Models
{
    public enum Department
    {
        ZealandRoskilde,
        ZealandNæstved,
        ZealandSlagelse,
        ZealandKøge,
        ZealandRingsted,
        ZealandHolbæk
    }
    [Table("Arrangement")]
    public partial class Arrangement
    {
     
        public Arrangement()
        {
            Bookings = new HashSet<Booking>();
            Events = new HashSet<Event>();
        }

        [Key]
        [Column("Arrangement_ID")]
        public int ArrangementId { get; set; }
        [Required(ErrorMessage = "Et arrangement navn skal udfyldes")]
        [StringLength(30)]
        [MinLength(3, ErrorMessage = "Navn på arrangement skal være mindst 3 bogstaver")]
        public string Name { get; set; }
        public Department Department { get; set; }
        [Column(TypeName = "datetime")]
        [Required(ErrorMessage = "Dato skal udfyldes")]
        public DateTime Date { get; set; }
        [StringLength(1000)]
        public string ImagePath { get; set; }

        [InverseProperty(nameof(Booking.Arrangement))]
        public virtual ICollection<Booking> Bookings { get; set; }
        [InverseProperty(nameof(Event.Arrangement))]
        public virtual ICollection<Event> Events { get; set; }
    }
}