// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ZealandEventLib.Models
{
    public enum Department 
    {
        ZealandRoskilde,
        ZealandNæstved
    }
    [Table("Arrangement")]
    public partial class Arrangement
    {
        public Arrangement()
        {
            Bookings = new HashSet<Booking>();
            Events = new HashSet<Event>();
        }

        [Key]
        [Column("Arrangement_ID")]
        public int ArrangementId { get; set; }
        [Required]
        [StringLength(100)]
        public string Name { get; set; }
        public Department Department { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Date { get; set; }

        [InverseProperty(nameof(Booking.Arrangement))]
        public virtual ICollection<Booking> Bookings { get; set; }
        [InverseProperty(nameof(Event.Arrangement))]
        public virtual ICollection<Event> Events { get; set; }
    }
}