// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ZealandEventLib.Models
{
    public enum UserRole { Admin, Guest}
    public partial class User
    {
        public User()
        {
            Bookings = new HashSet<Booking>();
        }

        [Key]
        [Column("User_ID")]
        public int UserId { get; set; }
        [Required]
        [StringLength(50)]
        public string UserName { get; set; }
        [Required]
        [StringLength(50)]
        public string Password { get; set; }
        public UserRole UserRole { get; set; }
        [Required]
        [StringLength(100)]
        public string Email { get; set; }

        [InverseProperty(nameof(Booking.User))]
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}