// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ZealandEventLib.Models
{
    public enum UserRole { Admin, Guest}
    public partial class User
    {
        public User()
        {
            Bookings = new HashSet<Booking>();
        }

        [Key]
        [Column("User_ID")]
        public int UserId { get; set; }
        [Required(ErrorMessage ="Brugernavn skal udfyldes")]
        [StringLength(30)]
        [MinLength(3, ErrorMessage = "Brugernavn skal bestå af mindst 3 bogstaver")]
        public string UserName { get; set; }
        [Required(ErrorMessage = "Kodeord skal udfyldes")]
        [StringLength(30)]
        [MinLength(6, ErrorMessage = "Kodeord skal bestå af mindst 6 bogstaver/tal")]
        public string Password { get; set; }
        public UserRole UserRole { get; set; }
        [Required(ErrorMessage = "Email skal udfyldes")]
        [StringLength(100)]
        [EmailAddress( ErrorMessage="Ugyldig e-mail")]
        public string Email { get; set; }

        [InverseProperty(nameof(Booking.User))]
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}